apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-scoring-api
  labels:
    app: credit-scoring-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: credit-scoring-api
  template:
    metadata:
      labels:
        app: credit-scoring-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-mlflow
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for MLflow at mlflow:5000..."
              until nc -z mlflow 5000; do sleep 3; done
              echo "MLflow port is open"
      containers:
        - name: api
          image: ghcr.io/nottmv/credit-scoring-api:4005325e8c737966791afbc6be0d6d0fc3c04340
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: MODEL_PATH
              value: "/app/models/model_bundle_catboost.pkl"
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
            - name: MLFLOW_MODEL_URI
              value: "models:/credit_scoring_catboost/Production"
            - name: MODEL_LOAD_RETRIES
              value: "24"
            - name: MODEL_LOAD_RETRY_DELAY
              value: "5"
            - name: EVENTS_JSONL_PATH
              value: "/app/reports/events.jsonl"
            - name: DRIFT_REPORT_PATH
              value: "/app/reports/last_drift.json"
            - name: CHAMPION_METRICS_PATH
              value: "/app/reports/champion_metrics.json"
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 25
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: reports
              mountPath: /app/reports
      volumes:
        - name: reports
          emptyDir: {}
