apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-scoring-api
  labels:
    app: credit-scoring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-scoring-api
  template:
    metadata:
      labels:
        app: credit-scoring-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api
          image: ghcr.io/nottmv/credit-scoring-api:1fc93594f40571415bd8c003e092c52d93424450
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
            - name: MLFLOW_MODEL_URI
              value: "models:/credit_scoring_catboost/Production"
            - name: EVENTS_JSONL_PATH
              value: "/app/reports/events.jsonl"
            - name: DRIFT_REPORT_PATH
              value: "/app/reports/last_drift.json"
            - name: CHAMPION_METRICS_PATH
              value: "/app/reports/champion_metrics.json"
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 25
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: reports
              mountPath: /app/reports
      volumes:
        - name: reports
          emptyDir: {}
