apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credit-scoring-api
  labels:
    app: credit-scoring-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: credit-scoring.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: credit-scoring-api
                port:
                  number: 8000
